apiVersion: apps/v1
kind: Deployment
metadata:
 name: accounts-depl
spec:
 replicas: 1
 selector:
  matchLabels:
   app: accountservice
 template:
  metadata:
   labels:
    app: accountservice
  spec:
   containers:
    - name: accountservice
      image: olumz1/zoollaraccountapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: accountservice
  ports:
    - protocol: TCP
      name: accountservice
      port: 80
      targetPort: 80