apiVersion: apps/v1
kind: Deployment
metadata:
 name: apigateway-depl
spec:
 replicas: 1
 selector:
  matchLabels:
   app: apigatewayservice
 template:
  metadata:
   labels:
    app: apigatewayservice
  spec:
   containers:
    - name: apigatewayservice
      image: olumz1/zoollarapigateway:latest
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apigatewayservice
  ports:
    - protocol: TCP
      name: apigatewayservice
      port: 80
      targetPort: 80