apiVersion: apps/v1
kind: Deployment
metadata:
 name: properties-depl
spec:
 replicas: 1
 selector:
  matchLabels:
   app: propertyservice
 template:
  metadata:
   labels:
    app: propertyservice
  spec:
   containers:
    - name: propertyservice
      image: olumz1/zoollarpropertiesapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: properties-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: propertyservice
  ports:
    - protocol: TCP
      name: propertyservice
      port: 80
      targetPort: 80