name: Continuous Integration and Deployment
on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 4
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "4.8.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore
