name: Continuous Integration and Deployment
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: Setup .NET 4
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "4.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore
